// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/zira-themes/Amber.tsx": () => import("../components/mockups/zira-themes/Amber.tsx"),
  "./components/mockups/zira-themes/Desert.tsx": () => import("../components/mockups/zira-themes/Desert.tsx"),
  "./components/mockups/zira-themes/Emerald.tsx": () => import("../components/mockups/zira-themes/Emerald.tsx")
};
